### ISSUE TITLE
CRS Not Installed via fleet

### ISSUE THREAD

**Issue by patrickbooth** [patrickbooth/fleet-cert-manager#1]
CRDs are not being installed when deploying cert-manager with fleet.

As a work around they have to be manually applied:

`$ kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.6.3/cert-manager.crds.yaml`

**Comment by longtomjr** [comment]
Hi, not sure if this is still relevant for you, but I came across this while trying to get cert manager to work with Fleet.

The CRDs deployed fine for me when I used the values field directly, instead of specifying the CRD values in the `targetCustomizations` or when using `valuesFrom`

Example:
```yaml
defaultNamespace: cert-manager
helm:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.16.1
  releaseName: cert-manager
  values:
    namespace: cert-manager
    crds:
      enabled: true
```

Just wanted to share if someone else stumbles on this in the future.
